Parameters:
  Bucket:
    Type: String
Resources:
  RolePermissionIdentity:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Principal: 
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - 's3:*'
            Resource:
              - 'arn:aws:s3:::${Bucket}/${cognito-identity.amazonaws.com:sub}'
              - 'arn:aws:s3:::${Bucket}/${cognito-identity.amazonaws.com:sub}/*'
          # - Sid: VisualEditor1
          #   Effect: Allow
          #   Action: 's3:ListBucket'
          #   Principal: 
          #     Federated: "cognito-identity.amazonaws.com"
          #   Resource: 'arn:aws:s3:::${Bucket}'
          #   Condition:
          #     StringLike:
          #       's3:prefix':
          #         - ''
          #         - /
          #         - '${cognito-identity.amazonaws.com:sub}/*'
          # - Sid: VisualEditor2
          #   Effect: Allow     
          #   Action:
          #     - 's3:ListAllMyBuckets'
          #     - 'kms:*'
          #     - 's3:GetBucketLocation'
          #   Resource: '*'
          # - Sid: VisualEditor3
          #   Effect: Allow
          #   Principal: 
          #     Federated: "cognito-identity.amazonaws.com"            
          #   Action: 's3:*'
          #   Resource:
          #     - 'arn:aws:s3:::${Bucket}/${cognito-identity.amazonaws.com:sub}'
          #     - 'arn:aws:s3:::${Bucket}/${cognito-identity.amazonaws.com:sub}/*'
