AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  daita-reference-image-service

  Sample SAM Template for daita-reference-image-service


Parameters:
  minimumLogLevel:
    Type: String
    Default: DEBUG
  Mode:
    Type: String
    Default: dev

  StagePara:
    Type: String
  ApplicationPara:
    Type: String

  CommonCodeLayerRef:
    Type: String
  LambdaRoleArn:
    Type: String

  TableAnnoDataOriginalName:
    Type: String 
  TableAnnoProjectSumName:
    Type: String
  TableAnnoProjectsName:
    Type: String
  TableLabelInfoName:
    Type: String
  TableCategoryInfoName:
    Type: String
  TableClassInfoName:
    Type: String
  TableAIDefaultClassInfoName:
    Type: String

  TableDaitaProjectsName:
    Type: String
  TableDaitaDataOriginalName:
    Type: String

  CognitoUserPoolRef:
    Type: String
  CognitoIdentityPoolIdRef:
    Type: String

  S3AnnoBucketName:
    Type: String
  S3DaitaBucketName:
    Type: String

Globals:
  Function:
    Timeout: 800   
    Runtime: python3.8
    Architectures:
      - x86_64 
    Layers:
      - !Ref CommonCodeLayerRef
    Environment:
      Variables:
        STAGE: !Ref StagePara        
        LOGGING: !Ref minimumLogLevel  
        MODE: !Ref Mode

        TABLE_ANNO_PROJECT_SUMMARY: !Ref TableAnnoProjectSumName
        TABLE_ANNO_PROJECT: !Ref TableAnnoProjectsName
        TABLE_ANNO_DATA_ORI: !Ref TableAnnoDataOriginalName
        TABLE_ANNO_LABEL_INFO: !Ref TableLabelInfoName
        TABLE_ANNO_CATEGORY_INFO: !Ref TableCategoryInfoName
        TABLE_ANNO_CLASS_INFO: !Ref TableClassInfoName
        TABLE_ANNO_AI_DEFAULT_CLASS: !Ref TableAIDefaultClassInfoName

        TABLE_DAITA_PROJECT: !Ref TableDaitaProjectsName
        TABLE_DAITA_DATA_ORIGINAL: !Ref TableDaitaDataOriginalName
        
        COGNITO_USER_POOL: !Ref CognitoUserPoolRef
        IDENTITY_POOL: !Ref CognitoIdentityPoolIdRef

        S3_ANNO_BUCKET_NAME: !Ref S3AnnoBucketName
        S3_DAITA_BUCKET_NAME: !Ref S3DaitaBucketName

Resources:
  #================ LAMBDA API FUNCTIONS ==========================================
  FunctionGetFileInfoNLabel:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-handler-functions/get-file-info-n-label
      Handler: hdler_get_file_info_n_label.lambda_handler
      Role: !Ref LambdaRoleArn
      MemorySize: 256

  FunctionCreateLabelCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-handler-functions/create-label-category
      Handler: hdler_create_label_category.lambda_handler
      Role: !Ref LambdaRoleArn
      MemorySize: 256

  FunctionSaveLabel:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-handler-functions/save-label
      Handler: hdler_save_label.lambda_handler
      Role: !Ref LambdaRoleArn
      MemorySize: 256

  FunctionAddClass:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api-handler-functions/add-class
      Handler: hdler_add_class.lambda_handler
      Role: !Ref LambdaRoleArn
      MemorySize: 256

  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api 
  FunctionGetFileInfoNLabelArn:
    Description: "FunctionGetFileInfoNLabelArn"
    Value: !GetAtt FunctionGetFileInfoNLabel.Arn
  FunctionCreateLabelCategoryArn:
    Value: !GetAtt FunctionCreateLabelCategory.Arn
  FunctionSaveLabelArn:
    Value: !GetAtt FunctionSaveLabel.Arn
  FunctionAddClassArn:
    Value: !GetAtt FunctionAddClass.Arn
  
  
