AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  daita-caller-service-app

  Sample SAM Template for daita-caller-service-app
Parameters:
  CallbackUrl:
    Type: CommaDelimitedList
  DomainUserPool:
    Type: CommaDelimitedList
  LogoutUrl:
    Type: CommaDelimitedList
  StagePara:
    Type: String
  Mode:
    Type: String
  LambdaRole:
    Type: String
  CommonCodeLayerName:
    Type: String
    
Globals:
  Function:
    Timeout: 800
    Handler: app.lambda_handler
    Runtime: python3.8
    Architectures:
      - x86_64
    Environment:
      Variables:
        STAGE: !Ref StagePara
        MODE: !Ref Mode
        COGNITO_CLIENT_ID: !Ref CognitoUserPool
        COGNITO_USER_POOL: !Ref CognitoUserPoolClient
    Layers:
        - !Ref CommonCodeLayerName
Resources:
######## lambda role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "lambda.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Policies:
        - PolicyName: 'SQS'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:*'
                Resource: '*'
        - PolicyName: 'SecretsManagerParameterAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParam*
                  - ssm:DescribeParam*
                Resource:
                  - arn:aws:ssm:*:*:parameter/*
        - PolicyName: 'CloudwatchPermission'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: 'CognitoPermission'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - cognito-identity:*
                  - cognito-idp:*
                Resource: '*'
        - PolicyName: 'DynamoDBPermission'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
        - PolicyName: "OtherServicePermission"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - events:PutEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - s3:*
                Resource: "*"
        - PolicyName: "InvokeFunction"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref AWS::StackName
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: user-pool-client
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs: !Split [',', !Join [',', !Ref CallbackUrl]]
      LogoutURLs: !Split [',', !Join [',', !Ref LogoutUrl]]
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 2
      RefreshTokenValidity: 24
      IdTokenValidity: 2
      TokenValidityUnits: 
          AccessToken: hours
          IdToken: hours
          RefreshToken: hours
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH       
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
  LoginFunction:
    Type:  AWS::Serverless::Function
    Properties:
      CodeUri: functions/login
      Role: !GetAtt LambdaExecutionRole.Arn
  
  RegisterFunction:
    Type:  AWS::Serverless::Function
    Properties:
      CodeUri: functions/sign_up
      Role: !GetAtt LambdaExecutionRole.Arn
  
  LoginRefreshTokenFunction:
    Type:  AWS::Serverless::Function
    Properties:
      CodeUri: functions/login_refresh_token
      Role: !GetAtt LambdaExecutionRole.Arn
  
  AuthConfirmFunction:
    Type:  AWS::Serverless::Function
    Properties:
      CodeUri: functions/auth_confirm
      Role: !GetAtt LambdaExecutionRole.Arn
  
  ConfirmCodeForgotPasswordFunction:
    Type:  AWS::Serverless::Function
    Properties:
      CodeUri: functions/confirm_code_forgot_password
      Role: !GetAtt LambdaExecutionRole.Arn
  
  GithubTokenWrapper:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/github_openid_token_wrapper
      Role:  !GetAtt LambdaExecutionRole.Arn
  
  GithubUserinfoWrapper:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/github_openid_userinfo_wrapper
      Role:  !GetAtt LambdaExecutionRole.Arn

  CredentialLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/credential_login
      Role:  !GetAtt LambdaExecutionRole.Arn
  
  LoginSocialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/login_social
      Role:  !GetAtt LambdaExecutionRole.Arn
  
  ResendCodeAuthConfirmCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/resend_confirmcode
      Role:  !GetAtt LambdaExecutionRole.Arn

Outputs:
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
  UserPool:
    Value: !Ref CognitoUserPool
  Login:
    Value: !Ref LoginFunction
  SignUp:
    Value: !Ref RegisterFunction
  LoginRefreshToken:
    Value: !Ref LoginRefreshTokenFunction
  AuthConfirm:
    Value: !Ref AuthConfirmFunction
  ResendCodeAuthConfirmCode:
    Value: !Ref ResendCodeAuthConfirmCodeFunction
  ConfirmCodeForgotPassword:
    Value: !Ref ConfirmCodeForgotPasswordFunction