openapi: "3.0.1"
info:
  title:
    Fn::Sub: "${StagePara}-Daita-HTTP-API"
  version: "2021-04-07"
tags:
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths: 
  /feedback/presign_url_image:
    post:
      responses:
        default:
          description: "check daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePresignUrlForImageFeedbackFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /cli/create_decompress_task:
    post:
      responses:
        default:
          description: "check daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateDecompressFileCLIFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /cli/check_existence_file:
    post:
      responses:
        default:
          description: "check daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CliCheckExistenceFileFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /cli/create_presignurl:
    post:
      responses:
        default:
          description: "check daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePresignUrlFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /cli/check_daita_token:
    get:
      responses:
        default:
          description: "check daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CheckDaitaTokenFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /cli/upload_project:
    post:
      responses:
        default:
          description: "generate daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CliUploadProjectFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /generrate/daita_upload_token:
    post:
      responses:
        default:
          description: "generate daita upload token"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GenertateTokenUploadProjectFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /generate/generate_images:
    post:
      responses:
        default:
          description: "generate images from data"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GenerateCheckConditionFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /generate/task_progress:
    post:
      responses:
        default:
          description: "get current progress of task"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TaskProgressFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /generate/list_method:
    post:
      responses:
        default:
          description: "get list method"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListMethodsFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /generate/split_data:
    post:
      responses:
        default:
          description: "update split data number"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SplitDataFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /task/stop_proceess:
    post:
      responses:
        default:
          description: "stop task process"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StopProcessTask.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  ###==============================
  ### For project functions
  /projects/apply_expert_mode_param:
    post:
      responses:
        default:
          description: "apply generate expert mode parameters"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApplyGenerateExpertParamFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"  

  /projects/delete_images:
    post:
      responses:
        default:
          description: "delete images"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteImages.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /projects/delete:
    post:
      responses:
        default:
          description: "delete project"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteProject.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  ####===================================================================================
  #### For healthcheck API
  /health_check/calculate:
    post:
      responses:
        default:
          description: "health check for dataset"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HealthCheckFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /health_check/status:
    post:
      responses:
        default:
          description: "Check status of task"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HCStatusFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /health_check/info:
    post:
      responses:
        default:
          description: "Get info of healthcheck"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HCInfoFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  ####===================================================================================
  #### For reference image API
  /reference_image/calculate:
    post:
      responses:
        default:
          description: "health check for dataset"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RICalculateFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /reference_image/status:
    post:
      responses:
        default:
          description: "Check status of task"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RIStatusFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /reference_image/info:
    post:
      responses:
        default:
          description: "Get info of healthcheck"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RIInfoFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  ####===================================================================================
  #### For augmentation image review

  /augmentation_review/get_aug_review:
    post:
      responses:
        default:
          description: "Get augmentation review image"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri: 
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetAugmentationImageReviewFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  ###===================================================================================
  ### For dataflow API
  /dataflow/create_decompress_task:
    post:
      responses:
        default:
          description: "create task for decompress zip file"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateDecompressTaskFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /dataflow/get_decompress_task:
    get:
      responses:
        default:
          description: "create task for decompress zip file"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDecompressTaskFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /dataflow/create_compress_download_task:
    post:
      responses:
        default:
          description: "create task for compress_download zip file"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateCompressDownloadTaskFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /dataflow/get_compress_download_task:
    post:
      responses:
        default:
          description: "get task for decompress zip file"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCompressDownloadTaskFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

  /task_dashboard/get_info:
    post:
      responses:
        default:
          description: "create task for decompress zip file"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TaskDashboardInfoFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

x-amazon-apigateway-cors:
  allowMethods:
  - "GET"
  - "OPTIONS"
  - "POST"
  allowHeaders:
  - "authorization"
  - "content-type"
  - "x-amz-date"
  - "x-amzm-header"
  - "x-api-key"
  - "x-apigateway-header"
  - "*"
  allowOrigins:
  - "*"
  maxAge: 60
  allowCredentials: false
x-amazon-apigateway-importexport-version: "1.0"