version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pemlzh8np33c"
s3_prefix = "sam-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "SecurityGroupIds=\"sg-af50cbde\" VpcId=\"vpc-53239e38\" SubnetId=\"subnet-31ff5b5a\" EFSFileSystemId=\"fs-0199771f2dfe97ace\" EFSMountPath=\"/mnt/efs\" EFSAccessPointRootPath=\"/decompress-app\" CognitoUserPoolId=\"us-east-2_ZbwpnYN4g\" CognitoIdentityPoolId=\"us-east-2:fa0b76bc-01fa-4bb8-b7cf-a5000954aafb\" S3BucketName=\"daita-client-data\""
