AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Nested application resources

Parameters:
  StagePara:
    Type: String

Resources:
    #================ DYNAMODB ==================================================
  GenerateTaskDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: identity_id
          AttributeType: S
        - 
          AttributeName: task_id
          AttributeType: S
      KeySchema:
        - 
          AttributeName: identity_id
          KeyType: HASH
        -
          AttributeName: task_id
          KeyType: RANGE
      TableName: !Sub "${StagePara}-generate-tasks"
      BillingMode: PAY_PER_REQUEST
Outputs:
  TableGenerateTaskName:
    Description: "Name of table generate task"
    Value: !Ref GenerateTaskDB
  TableProjectsName:
    Description: "Name of table projects"
    Value: projects
  TableMethodsName:
    Description: "Name of table methods"
    Value: methods
