openapi: "3.0.1"
info:
  title:
    Fn::Sub: "${StagePara}-${ApplicationPara}-HTTP-API"
  version: "2021-04-07"
tags:
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths:
  ###=== for project =====###
  /annotation/project/clone_from_daita:
    post:
      responses:
        default:
          description: "Clone project from daita"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProjectCloneFunctionArn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"

x-amazon-apigateway-cors:
  allowMethods:
  - "GET"
  - "OPTIONS"
  - "POST"
  allowHeaders:
  - "authorization"
  - "content-type"
  - "x-amz-date"
  - "x-amzm-header"
  - "x-api-key"
  - "x-apigateway-header"
  - "*"
  allowOrigins:
  - "*"
  maxAge: 60
  allowCredentials: false
x-amazon-apigateway-importexport-version: "1.0"