AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Nested application resources

## The general rule seems to be to use !Sub for in line substitutions and !ref for stand alone text
Parameters:
 
  Stage:
    Type: String
    Default: test
  
  ImageSegmentUrl:
    Type: String
    Default: 737589818430.dkr.ecr.us-east-2.amazonaws.com/ai-services-repo:segformer

Resources:


  #================ APPLICATIONS  =============================================
  NetworkLayerApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./network.yaml
      Parameters:
        StagePara: !Ref Stage

  RoleApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./role.yaml 
  
  ServiceApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./service.yaml
      Parameters:
        EC2Role: !GetAtt RoleApplication.Outputs.EC2Role
        PublicSubnetOne: !GetAtt NetworkLayerApplication.Outputs.PublicSubnetOne
        PublicSubnetTwo: !GetAtt NetworkLayerApplication.Outputs.PublicSubnetTwo
        ContainerSecurityGroup: !GetAtt NetworkLayerApplication.Outputs.ContainerSecurityGroup
        ExecuteArn: !GetAtt RoleApplication.Outputs.ECSTask
        StagePara: !Ref Stage
        TaskRole: !GetAtt RoleApplication.Outputs.ECSRole
        ImageUrl: !Ref ImageSegmentUrl
  
