AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Nested application resources

## The general rule seems to be to use !Sub for in line substitutions and !ref for stand alone text
Parameters:
 
  Stage:
    Type: String
    Default: test
    
Resources:


  #================ APPLICATIONS  =============================================
  ECSServiceApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template_ecs.yaml
      Parameters:
        StagePara: !Ref Stage

  InvokeServiceApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./template_invoke.yaml
      Parameters:
        StagePara: !Ref Stage
        AITaskECSClusterArn: !GetAtt ECSServiceApp.Outputs.AITaskECSClusterArn
        AITaskDefinitionArn: !GetAtt ECSServiceApp.Outputs.AITaskDefinitionArn
        LsPrivateSubnetIDs: !GetAtt ECSServiceApp.Outputs.LsPrivateSubnetIDs
  


  
