service: dev-backend-daita

frameworkVersion: '2'

provider:
  versionFunctions: false
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  stage : staging
  iam:
    role: arn:aws:iam::737589818430:role/datai_be_roles_1

package:
  patterns:
    - '!./**'
    - ./bin/**

#resources:
#  Resources:
#####################################################
#    eventIDDynomoDBTable:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        TableName: eventUser
#        AttributeDefinitions:
#          - AttributeName: event_ID
#            AttributeType: S
#        KeySchema:
#          - AttributeName: event_ID
#            KeyType: HASH
#
#####################################################
#    userDynomoDBTable:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        TableName: User
#        AttributeDefinitions:
#          - AttributeName: ID
#            AttributeType: S
#          - AttributeName: username
#           AttributeType: S
#        KeySchema:
#          - AttributeName: ID
#            KeyType: HASH
#          - AttributeName: username
#            KeyType: RANGE

functions:
  login:
    handler: bin/login
    events:
      - http:
          path: /user_login
          method: post
          cors: true
  sign_up:
    handler: bin/sign_up
    events:
      - http:
            path: /user_signup
            method: post
            cors: true
  sign_out:
    handler: bin/sign_out
    events:
      - http:
          path: /user_logout
          method: post
          cors: true
  test:
    handler: bin/test
    events:
      - http:
          path: /test
          method: post
          cors: true

  auth_confirm:
    handler: bin/auth_confirm
    events:
      - http:
          path: /auth_confirm
          method: post
          cors: true

  resend_confirmcode:
    handler:  bin/resend_confirmcode
    events:
      - http:
          path: /resend_confirmcode
          method: post
          cors: true
  confirm_code_forgot_password:
    handler: bin/confirm_code_forgot_password
    events:
      - http:
          path: /confirm_code_forgot_password
          method: post
          cors: true
  forgot_password:
    handler: bin/forgot_password
    events:
      - http:
          path: /forgot_password
          method: post
          cors: true
  refresh_token:
    handler: bin/login_refresh_token
    events:
      - http:
          path: /refresh_token
          method: post
          cors: true
  template_email:
    handler: bin/template_email
    events:
      - http:
          path: /template-invite-mail
          method: get
          cors: true
  login_social:
    handler: bin/login_social
    events:
      - http:
          path: /login_social
          method: get
          cors: true
