openapi: "3.0.1"
info:
  title:
    Fn::Sub: "${StagePara}-Daita-HTTP-API"
  version: "2021-04-07"
tags:
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths:
  /auth/login-social:
    post:
      responses:
        default:
          description: "Auth service transport"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginSocialFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
    