openapi: "3.0.1"
info:
  title:
    Fn::Sub: "${StagePara}-Daita-Auth-HTTP-API"
  version: "2021-04-07"
tags:
- name: "httpapi:createdBy"
  x-amazon-apigateway-tag-value: "SAM"
paths:
  /auth/login_social:
    get:
      responses:
        default:
          description: "Auth service transport"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginSocialFunction.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /auth/github-openid-userinfo-wrapper:
    get:
      responses:
        default:
          description: "Auth service transport"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GithubUserinfoWrapperFunc.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
    post:
      responses:
        default:
          description: "Auth service transport"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GithubUserinfoWrapperFunc.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"
  /auth/github-openid-token-wrapper:
    get:
      responses:
        default:
          description: "Auth service transport"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GithubTokenWrapperFunc.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0" 
    post:
      responses:
        default:
          description: "Auth service transport"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ApiGatewayCallLambdaRole, Arn]
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GithubTokenWrapperFunc.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
        payloadFormatVersion: "2.0"     